### ISSUE TITLE
Using the OTDefaultAudioDevice breaks AirPlay support

### ISSUE THREAD

**Issue by zilppuri** [opentok/opentok-ios-sdk-samples#162]
In the latest OpenTok version (2.12.0) from September 2017, fixes to AirPlay support were introduced. However, if using the OTDefaultAudioDevice.h and OTDefaultAudioDevice.m files and using them as an audio driver, the AirPlay support is broken.

I am unable to choose any AirPlay devices for mirroring if using this driver and streaming from TokBox. However, if I do make some changes (mainly change the session category to AVAudioSessionCategoryPlayback - as we do not use microphone input from our end users), the mirroring does work. But only for about 20-30 seconds, and then the connection is lost.

Would it be possible to update the audio driver examples to match the 2.12.0 OpenTok version - meaning having an example where the AirPlay streaming does work.

**Comment by robjperez** [comment]
Hi!

The audio device files in the Custom-Audio-Driver has been updated.

Closing this ticket, please reopen it if current files still breaks AirPlay

Regards
