### ISSUE TITLE
How to set the "return to call" status bar title?

### ISSUE THREAD

**Issue by markymc** [opentok/opentok-ios-sdk-samples#164]
Hi guys,

Is it possible to set the title of the double height status bar that appears when backgrounding your app while in a call? I'm having trouble finding any mention of it in the Apple documentation.

If this is possible, I'd appreciate some guidance on how to do it.

Thanks!

**Comment by robjperez** [comment]
Hi,

The bar shown on iOS when an App is in a call or recording audio is handled by iOS itself and it is not possible to customize it.

Closing this issue.

Regards

**Comment by markymc** [comment]
Understood. Thanks for your assistance @robjperez.
