### ISSUE TITLE
OTAudioDeviceRingtone not working

### ISSUE THREAD

**Issue by chitvan832** [opentok/opentok-ios-sdk-samples#165]
i have implemented the same code from sample project still there is no sound which making a video call

**Comment by robjperez** [comment]
Hi!

Can you elaborate a little bit on the problem your are having?

Depending on your use case, our CallKit sample can help too: https://github.com/opentok/CallKit

**Comment by robjperez** [comment]
Going to close this due to inactivity. If the problem is still there, please reopen the issue
