### ISSUE TITLE
Build problems with Opentok.framework file.

### ISSUE THREAD

**Issue by tejasna** [opentok/opentok-ios-sdk-samples#166]
Hi,
I recently had to add a Cocoa Touch Framework in my iOS project (Swift 3.0) which uses OpenTok as an internal dependency. Everything works great, but the only problem i'm having is my build on CircleCI. We use Fastlane and CircleCI to distribute our app to various environments. And since the Opentok.framework(static library) is 130MB in size and GitHub has a limit of 100MB, i'm having trouble to make my builds work on CircleCI. Would you please suggest a work around maybe. Appreciate any sort of help.  
   
With thanks in advance,
Tejas

**Comment by robjperez** [comment]
Hi!

First of all, sorry about the delay answering the issue.

I'm not sure I understand your whole set up, but I would suggest you to not upload the library to github and install it via CocoaPods where the application is built.

If you still need to upload it, the `OpenTok` file is a `fat` library, that means that it contains several archs inside, 
```
file OpenTok
OpenTok: Mach-O universal binary with 5 architectures: [i386:current ar archive random library] [arm64]
OpenTok (for architecture i386):	current ar archive random library
OpenTok (for architecture armv7):	current ar archive random library
OpenTok (for architecture armv7s):	current ar archive random library
OpenTok (for architecture x86_64):	current ar archive random library
OpenTok (for architecture arm64):	current ar archive random library
```

With the [`lipo`](http://www.manpages.info/macosx/lipo.1.html) tool , you can remove some archs that you don't plan to use (like the x86 or i386 ones)

Hope it helps.
