### ISSUE TITLE
The provided API key does not match this token

### ISSUE THREAD

**Issue by Hassan-Aftab** [opentok/opentok-ios-sdk-samples#173]
I am trying Signaling app provided in this repo. I have added valid token, session id and api keys. But I am getting this error 

`(Error Domain=OTSessionErrorDomain Code=1004 "The provided API key does not match this token" UserInfo={NSLocalizedDescription=The provided API key does not match this token})`

**Comment by msach22** [comment]
@Hassan-Aftab This is not an issue with this repo, it looks like the token you created is linked to a different API Key than the one you're trying to use. Please either use one of our [server sdks](https://tokbox.com/developer/sdks/server/) or account dashboard to generate the credentials.

**Comment by amerragab848** [comment]
message: "Authentication Error: The API key does not match the token or session. (1004)" when i use opentok

**Comment by JandroMejia97** [comment]
Hi, I have the same error. But, in my interface I have the same API key that I use in my backend. :cry: 
![image](https://user-images.githubusercontent.com/32623757/142208224-0ed713d5-0b68-41ef-bdc2-881426c00499.png)
