### ISSUE TITLE
Swift Compiler errors

### ISSUE THREAD

**Issue by Shrutimittal91** [opentok/opentok-ios-sdk-samples#198]
I am using OpenTok version 2.16
And frequently while compiling i face the issue

<img width="806" alt="Screenshot 2019-11-19 at 12 22 08 PM" src="https://user-images.githubusercontent.com/8266611/69123437-5d66a880-0ac7-11ea-87db-31ddb963a8eb.png">

Though sometime it works if i clean the project 5 6 times but this issue is very frequent.

**Comment by GRyabkin** [comment]
I have the same problem
