### ISSUE TITLE
BroadcastUpload SampleHandler.m swift conversion

### ISSUE THREAD

**Issue by eliang** [opentok/opentok-ios-sdk-samples#200]
I am trying to convert the SampleHandler to Swift 3 and I'm running into the following challenges:

How do you define the `videoCaptureConsumer` in SampleHandler.h?

https://github.com/opentok/opentok-ios-sdk-samples/blob/754aedc9d143cf7eb8c09b4f49b44018f72d9ced/Broadcast-Ext/OpenTok%20Live/SampleHandler.h#L17

https://github.com/opentok/opentok-ios-sdk-samples/blob/754aedc9d143cf7eb8c09b4f49b44018f72d9ced/Broadcast-Ext/OpenTok%20Live/SampleHandler.m#L92-L95

Swift suggests the following template, but what should be returned?

```
	var videoCaptureConsumer: OTVideoCaptureConsumer? {
		get {
			<#code#>
		}
		set(videoCaptureConsumer) {
			<#code#>
		}
	}
```

**Comment by fabiocody** [comment]
As far as I understood, it gets automatically instantiated by OpenTok once you assign your `OTVideoCapture` instance to a publisher. I leave it as
```swift
var videoCaptureConsumer: OTVideoCaptureConsumer? 
```
and it works.
