### ISSUE TITLE
FrameMetadata doesn't actually work?

### ISSUE THREAD

**Issue by znelson32** [opentok/opentok-ios-sdk-samples#210]
Obj-C FrameMetadata doesn't actually send metadata to remote subscribers. It all appears to be a local loop-back in the example project. When I connect the Windows SDK to the same session, the frame.metadata is null. Or maybe this is just the same problem as below:

Swift FrameMetadata doesn't work either.. but sometimes when I set a breakpoint in the Windows client and inspect the frame.metadata property (it's null) and then step over suddenly there's metadata. But the timestamps start repeating, the same two timestamps over and over.  Then, with the FrameMetadata app still running on the phone, I disconnect the Windows client from the OT Session and reconnect, no metadata again. 

I create a new Session and Token, video is working between Windows and iOS clients but no metadata. Suddenly the metadata shows up but it's more than 30 seconds old and it keeps repeating. Everything has been running now for 5 mins and I keep getting this in the Windows client over and over: 2020-05-11T03:26:28-04:00

Now I'm getting this over and over:
Subscriber video frame metadata: 2020-05-11T03:30:13-04:00
Subscriber video frame metadata: 2020-05-11T03:26:28-04:00
Subscriber video frame metadata: 2020-05-11T03:28:58-04:00
Subscriber video frame metadata: 2020-05-11T03:30:13-04:00

Is this a server issue? The only changes I've made to all the example code is the Key, SessionId, and Token.

**Comment by IGitGotIt** [comment]
Hi @znelson32 

Looks like our previous changes dropped a callback that fetched the metadata value.  I have merged the fix -  https://github.com/opentok/opentok-ios-sdk-samples/commit/3de3a1c6555751203b52c0f42bfe606b9b4d5ca9

I also added a `label` at the bottom to show the subscriber frame metadata string :
![image](https://user-images.githubusercontent.com/4369083/81747649-4cd33180-945d-11ea-82c2-0d6f1e7c3e61.png)

I was not able to duplicate the repetitive timestamps values. 

Can you please give it a try with the new code.

Thanks

**Comment by znelson32** [comment]
Thanks @IGitGotIt - I gave the new code a try and see the metadata on the Publisher side of things on the iOS app. But the videoFrame.Metadata is still null on theSubscribers who use the Windows clients. Isn't the metadata supposed to be transmitted on video frames to all Subscribers in the session?
