### ISSUE TITLE
Set Subscriber Audio Volume

### ISSUE THREAD

**Issue by RockinGarg** [opentok/opentok-ios-sdk-samples#213]
Hi,

I have been trying to set OTSubscriber or OTSession Volume Level like you have in js
**subscriber.setAudioVolume**

Issue: As Soon as Subscriber is connected. Volume keys control the volume of Session but I need to control volume using a UISlider in iOS Natively.

Can you please tell me how I can control session Audio volume using a UISlider or MPVolumeView of iOS ?
I need this urgently

Thanks

**Comment by znelson32** [comment]
I don't believe there's a working example of controlling the subscriber audio. I'm trying to figure out the same thing. I need a way to individually control the volume of everyone in the call in objective-C, in a similar way as in the javascript API. Hopefully someone on the OpenTok team can point us in the right direction.

**Comment by RockinGarg** [comment]
I talked to OpenTok Support Team, They Confirmed that currently they don't support this feature.
