### ISSUE TITLE
Important changes to iOS 14 networking affecting relayed sessions 

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-ios-sdk-samples#217]
With iOS 14, Apple introduces local network privacy ([see this video](https://developer.apple.com/videos/play/wwdc2020/10110)).

Beginning in iOS 14, the operating system will prompt the user for permission when an application attempts to subscribe to clients on the same local network in a [relayed session](https://tokbox.com/developer/guides/create-session/#media-mode).

If your application uses a relayed session, it is encouraged to add a descriptive custom usage string to inform the user why the application needs access to their local area network. The Vonage Video API uses the local network to discover and connect to video participants on your same network where possible. The Apple video (above) shows how you can edit the string displayed in this message.

If the user does not accept the permission, the attempt to subscribe will fail. After the permission is rejected, any future attempts to subscribe to clients on the same network will also fail unless the user changes the permission in Settings. Unfortunately, iOS does not provide an API for an application to determine if the user has accepted or rejected this permission.

It is important to note that this does not apply to video sessions that use the [OpenTok Media Router](https://tokbox.com/developer/guides/create-session/#media-mode), as media is sent over the internet rather than the local network.

For applications which cannot use routed sessions and do not wish the user to ever be prompted for local network access, it is recommended to use TURN by using the following API:

```
   OTSessionICEConfig *myICEServerConfiguration = [[OTSessionICEConfig alloc] init];
 
    OTSessionSettings *settings = [[OTSessionSettings alloc] init];
    myICEServerConfiguration.transportPolicy = OTSessionICETransportRelay;
    settings.iceConfig = myICEServerConfiguration;
    _session = [[OTSession alloc] initWithApiKey:kApiKey
                                       sessionId:kSessionId
                                        delegate:self settings:settings];
```

**Comment by janoonaj** [comment]
Thanks a lot for your message. 

Do you know if Vonage Video API uses Bonjour?

Thanks a lot
