### ISSUE TITLE
Extension Crashes on iPad Mini with ios 14.x

### ISSUE THREAD

**Issue by predictcare** [opentok/opentok-ios-sdk-samples#234]
Hi, the extension keeps crashing and closing on iPad Mini.

Same code works on iPhone x and 8+, so i think that maybe the system closes it because it is over 50Mb.

How can i shrink resolution ? Can you please point me in the right direction so i can try if the extension si being killed ?

Thanks.

**Comment by predictcare** [comment]
Hi all, after many testing we found that the total memory footprint of the extension is way too high and gives almost no space for any other activity. Is there any way to reduce this footprint of the extension ? Can someone at Vonage gives us a real support ? We've been using Opentok/Vonage for years and we think we could deserve an help here (not only a : "can we set up a professional development team for you ? ).  Thanks

**Comment by mehmetbaykar** [comment]
Any update on that?

Can you guys please give support on Broadcast Extension?

The sample code does not work any of the Apple device I used(iPhone 6, iPhone 11, iPad Pro 3rd)

Please
