### ISSUE TITLE
Open Tok ReplayKit Integration

### ISSUE THREAD

**Issue by mehmetbaykar** [opentok/opentok-ios-sdk-samples#239]
Hi @robjperez , 

The screen-sharing module contains an old code base also there is no swift support for it. Can you please provide a swift example of the module with latest updates of OpenTok.

Best,

**Comment by mehmetbaykar** [comment]
At least could you please fix the bugs on the SampleHandler.m?

As you can see 
<img width="358" alt="Screenshot 2021-08-20 at 19 51 52" src="https://user-images.githubusercontent.com/20362928/130267422-81d3dcff-91fe-4590-8ce3-7bba0b67c7c1.png">
the video ideo is corrupted when transmitting it.

**Comment by mehmetbaykar** [comment]
I checked it and turns out that it happens only SDK Version above 2.18.1 @abdulajet

**Comment by mehmetbaykar** [comment]
Before Closing the issue, please kindly give a reply first, so other developers will know what to do next.

**Comment by v-kpheng** [comment]
@mehmetbaykar, I'm sorry.

I did a bulk close of all issues that were older than a year, basically.
