### ISSUE TITLE
Missing arm64 simulator slice in OpenTok.xcframework

### ISSUE THREAD

**Issue by jweg29** [opentok/opentok-ios-sdk-samples#248]
Hello, I'm getting an error similar to his post when trying to profile my app against a simulator using Xcode 13: https://developer.apple.com/forums/thread/674716.

It appears that the solution proposed by Apple is to have the OpenTok.xcframework contain an arm64 slice for both simulators and devices. Is this something that you can work on?

Thank you!

**Comment by filip-ic** [comment]
Hi, please add arm64 simulator slice to the xcframwork so we can run the iOS simulator on M1 Macs. Thanks

**Comment by egarni** [comment]
Same problem here, please fix. thanks

**Comment by dtaradaika** [comment]
Same problem, looking for support arm64.

**Comment by BratislavBaljakShyft** [comment]
Got the same problem, please fix this.

**Comment by ben-palmer** [comment]
It's been since November 2020 since this hardware became available. What's the holdup?

**Comment by StanRosenbaum98point6** [comment]
Any update on a timeline with arm64 will be ready?

**Comment by falkobuttler** [comment]
Well, the release notes said they would add it with the 2.23 release. Now this release dropped in early July and it still doesn't have it, which is quite disappointing. We're almost a year into having M1 macs at this point...
