### ISSUE TITLE
How can we detect the real reason behind the subscriber's video disabled due to quality change?

### ISSUE THREAD

**Issue by gowtham1094** [opentok/opentok-ios-sdk-samples#251]
We can detect the subscriber video disabled from a protocol with a reason why it got disabled. 
One of the reason for disabling is `Quality Changed` 

<img width="724" alt="Screenshot 2021-10-25 at 10 19 22 AM" src="https://user-images.githubusercontent.com/55850929/138636292-bbf0e784-e6ec-464b-ae5d-bde355abdc86.png">

As per the documentation this quality changed would be trigger whenever quality of network/cpu degraded on either publisher/subscriber device. How do we know the exact reason here, like which device has the problem so that we can inform user that either your's or your partner's device has lower bandwidth. Which help users to have better knowledge why the video feed got suspended. 

<img width="726" alt="Screenshot 2021-10-25 at 10 19 05 AM" src="https://user-images.githubusercontent.com/55850929/138636310-cfb17dde-4bb2-4d21-9116-0ca46ec49bd8.png">

Is there any api which can tell more detail about this quality change trigger?

**Comment by abdulajet** [comment]
Ive reached out to engineering for some clarification
