### ISSUE TITLE
Broadcast extension invalid session

### ISSUE THREAD

**Issue by ledinhthi** [opentok/opentok-ios-sdk-samples#253]
Today, i try to stream screen sharing. but had problem, stream always is broken, and audio is distorted. Anyone, have any solution to scale image?, Thank you so much

**Comment by v-kpheng** [comment]
Thanks, @ledinhthi, for filing this issue.

I wonder if the issue you're seeing is related to https://github.com/opentok/opentok-ios-sdk-samples/issues/256.  Closing, since I suspect that it is.

If you feel otherwise, please let us know.  Thanks!
