### ISSUE TITLE
delegate publisher(_:didFailWithError:) 'Timed out while attempting to publish .'

### ISSUE THREAD

**Issue by FaizanLN** [opentok/opentok-ios-sdk-samples#256]
video broadcasting is getting disconnected after 17 sec every time with Error message ![Error Alert](https://user-images.githubusercontent.com/97291433/155497847-98806cca-8b52-4812-a680-447d0efe1f0c.png)delegate publisher(_:didFailWithError:)
I am facing issue on video broadcasting.
I'm using iPhone 12 Pro version iOS 15.2.1 and iPhone 12 Pro Max version iOS 15.2.1.
Opentok SDK verion is '2.21.3'

**Comment by martinfreefall** [comment]
Are you checking the connection strength before ?

**Comment by FaizanLN** [comment]
I have tested this SDK on different devices and on different versions of iOS this SDK is working as expected but on "iPhone 12 Pro version iOS 15.2.1 and iPhone 12 Pro Max version iOS 15.2.1" video broadcast getting disconnect

**Comment by martinfreefall** [comment]
if you are using  OTDefaultAudioDevice. Try reusing the same object before every session 

 let appdel = UIApplication.shared.delegate as! AppDelegate
        OTAudioDeviceManager.setAudioDevice(appdel.globalAudioDevice )
        session = OTSession(apiKey: kApiKey, sessionId: kSessionId, delegate: self)

**Comment by Adza93** [comment]
> 

@martinfreefall  I am experiencing the same issue on pod 'OTXCFramework', '~> 2.22.3'
iPhone 12 Pro Max iOS 15.5

After performing Network Test https://github.com/opentok/opentok-network-test/tree/master/iOS-Sample 
and then initializing session as per example https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Basic-Video-Chat I am getting error Timed out while attempting to publish after trying to publish client session to server side.

If I skip part of network testing main session call works fine. I do not experience same issue with Android framework. Your quoted instructions did not help. I have tried to share object instances and not to share them (to use 2 separate classes for test network and main call) but the problem still persists. Could you give any additional comment or workaround I could try? Thanks!

**Comment by v-kpheng** [comment]
Thanks, everyone, for filing this issue.  We're tracking this internally via https://jira.vonage.com/browse/OPENTOK-49175.

**Comment by v-kpheng** [comment]
Closing the loop, for broadcast, please use an H264 enabled API key.  More details here: https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Broadcast-Ext
