### ISSUE TITLE
OTSubscriberKitDelegate methods not being called

### ISSUE THREAD

**Issue by Lukelear-Warhead** [opentok/opentok-ios-sdk-samples#259]
In particular, I am unable to get "subscriberDidDisconnectFromStream" and "subscriberDidReconnectToStream" to run when I have a device that loses network stability. Those specific methods only trigger on the device that is experiencing the network problem. Suggesting every other subscriber is having trouble connecting to the session. This is not what is implied in the [documentation](https://tokbox.com/developer/sdks/ios/reference/Protocols/OTSubscriberKitDelegate.html#//api/name/subscriberDidReconnectToStream:).

**Comment by v-kpheng** [comment]
@chetanvangadiTokbox, @pvenum, do you see this as well?  If so, maybe we should update our documentation.

Please advise.  Thanks!

**Comment by v-kpheng** [comment]
@chetanvangadiTokbox, @pvenum, nm.  I created a tracking ticket to investigate: https://jira.vonage.com/browse/OPENTOK-49169.

**Comment by josemrecio** [comment]
@Lukelear-Warhead  the methods are triggered on the subscriber object on the client which is disconnected.
The intention is to let the developer know that the subscriber object has lost or recovered connectivity, to take appropriate actions (UX indication, etc).
So, if we have:
- client C1 publishing stream S1
- client C2 subscribing to stream S1, subscriber object O2
- client C3 subscribing to stream S1, subscriber object O3
If C2 has connectivity issues and O2 loses stream S1, the events would be raised. This does NOT mean that client C1 has any connectivity problem. O3 would not raise any event, as client C3 did not lose access to stream S1. 
> Suggesting every other subscriber is having trouble connecting to the session.
I don't understand this

**Comment by v-kpheng** [comment]
Thanks, @josemrecio.  Good point :-)

Closing.
