### ISSUE TITLE
Thread warning when initialising OTPublisher

### ISSUE THREAD

**Issue by badarovska** [opentok/opentok-ios-sdk-samples#267]
Initialising an OTPublisher freezes the main thread for a short time and prints out the fallowing warning: 

Thread Performance Checker: -[AVCaptureSession startRunning] should be called from background thread. Calling it on the main thread can lead to UI unresponsiveness. 

Initialising the OTPublisher creates and starts AVCaptureSession. 
 [AVCaptureSession startRunning] method is synchronous and blocks until the session starts running. It should be called from background thread.

**Comment by v-kpheng** [comment]
Thanks, @badarovska, for filing this issue.

Any ideas, @jvalli?  Please advise.  Thanks! 🙏

**Comment by jvalli** [comment]
Hi @badarovska! We are doing the AVCaptureSession initialization and start running action everything on a secondary thread, that message sounds weird. What version of the library are you working with? Any particular sample app? Thanks!

**Comment by badarovska** [comment]
Hi @jvalli,  
I am using the latest version of the iOS library OpenTok (2.23.1). It is reproducible on the Basic-Video-Chat example (https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Basic-Video-Chat). Just starting the app on my device with valid credentials triggers the warning. The thread checked in XCode marks the init publisher method and the backtrace is shown in the console. I've added attachments below. 

The warning started appearing after updating to XCode 14.0. 

![Screenshot 2022-09-22 at 15 40 53](https://user-images.githubusercontent.com/17143444/191767975-d0c58886-e438-4eda-9dae-f680f0da8c0f.png)

![Screenshot 2022-09-22 at 15 56 29](https://user-images.githubusercontent.com/17143444/191767981-3226b652-07da-47c4-a890-1e0d0e120e03.png)

**Comment by jvalli** [comment]
@v-kpheng Can we have a new ticket to investigate this message? Thanks!

**Comment by v-kpheng** [comment]
@jvalli, let's use https://jira.vonage.com/browse/OPENTOK-49122 please.  Thanks! 🙏

**Comment by v-kpheng** [comment]
👋 , FYI, the fix should arrive in the next release, iOS SDK 2.24.0.  Closing.
