### ISSUE TITLE
Subscriber Video Enabling Problem

### ISSUE THREAD

**Issue by cemkazim** [opentok/opentok-ios-sdk-samples#271]
When we activate the video after starting the conversation by enabling only the audio stream without enabling the video, the subscriberView doesn't appear on the iOS app. But when we go background and foreground just once, the video has appeared on the view.

If subscriber video opens, we want to see it in view.

- iOS SDK version: 2.24.0
- OS and version: 16.0

**Comment by v-kpheng** [comment]
@abdulajet , any updates?

**Comment by beHaze** [comment]
Closing. If you can repro with a more recent version please reopen.
