### ISSUE TITLE
Crash: OTSession initWithToken:error:

### ISSUE THREAD

**Issue by DimaIgorevich** [opentok/opentok-ios-sdk-samples#275]
**Describe the bug**
When I'm start working with connect session via token, after init flow of OTSession instance catch the crash.
It start raise error when update OpenTok version from 2.21.3 to 2.22.0 or 2.23.0 or 2.24.0

**To Reproduce**
Related to sdk version 2.22.0

OTError *result = nil;

if (session.sessionConnectionStatus == OTSessionConnectionStatusConnected) { return; }

[session connectWithToken:token error:&error];

Application(11135,0x170373000) malloc: *** error for object 0x2822a1b48: pointer being freed was not allocated
Application(11135,0x170373000) malloc: *** error for object 0x2822a1b48: pointer being freed was not allocated
Application(11135,0x170373000) malloc: *** set a breakpoint in malloc_error_break to debug

**Screenshots**

**Device (please compete the following information):**
- OpenTok: 2.22.0
- OS and version: 16.1

On version 2.21.3 all works fine.

**Comment by IGitGotIt** [comment]
Does this happen with any session id  and token combination?  Can you try with a new set of credentials?
Do you have the crash trace? (Output of `bt all` console command will help.)
Thanks

**Comment by DimaIgorevich** [comment]
Hello, yes with different session and token it happens.
Crash trace:

thread #1, queue = 'com.apple.main-thread'
    frame #0: 0x00000001f3d7241c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000002041db06c libsystem_pthread.dylib`_pthread_cond_wait + 1232
    frame #2: 0x0000000100f49954 Application Connect`otk_thread_cond_wait + 64
    frame #3: 0x0000000100f5983c Application Connect`otk_ev_send_msg_sync + 360
    frame #4: 0x0000000100f5a3f4 Application Connect`otk_session_connect + 76
    frame #5: 0x0000000100f6a794 Application Connect`otc_session_connect_to_host + 128
    frame #6: 0x0000000100f0952c Application Connect`-[OTSession connectWithToken:error:] + 348
    frame #7: 0x0000000100c79160 Application Connect`-[OpenTokConference enableConnectionWithToken:](self=0x000000028004cdd0, _cmd="enableConnectionWithToken:", token=@"T1==cGFydG5lcl9pZD00NjA1NTM5MiZzaWc9ODI1MWJjNGUyNDc0Mjg4Mjc0ZDlmMGM5YTVjNTQ1ZTAyMjAwOGM3MjpzZXNzaW9uX2lkPTJfTVg0ME5qQTFOVE01TW40eUxqSXhMamc1TGpCLU1UWTNORFkwTVRrd01UZ3hNSDUxT1VGMFdVcHFNVlZzYWpFM2RIVkhPQzh4S3k5NGFuWi1mbjQmY3JlYXRlX3RpbWU9MTY3NDY0ODgxNiZub25jZT0tMTI4NDE5MTM0OCZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNjc1MjUzNjE2JmNvbm5lY3Rpb25fZGF0YT0rKysrJTdCJTIybmFtZSUyMiUzQSslMjJEaW1wJTIyJTJDJTBBKysrKyUyMnJvbGUlMjIlM0ErJTIyVUlfSU5URVJQUkVURVIlMjIlMkMlMEErKysrJTIyY2hhaXJwZXJzb24lMjIlM0ErZmFsc2UlMkMlMEErKysrJTIyYXV0aFRva2VuJTIyJTNBKyUyMmV5SmhiR2NpT2lKSVV6VXhNaUo5LmV5SmxlSEFpT2pFMk56UTJPVGt5TVRBc0ltcDBhU0k2SWpsbE4yRXpaREprTFdJelptWXRORGN4WWkxaU5XTmhMVGMyWkRVM1pqbG1NekV6TWlJc0luTjFZaUk2SWtScGJYQWlMQ0pwYzNNaU9pSlZTVjlKVGxSRlVsQlNSVlJGVWlJc0ltVjJaVzUwU1dRaU9pSm1PV0l5TlRBNU15MDJOekF6TFRRek5qSXRZVGxoTUMxak9HVTFNRGRqT0RGa1pqZ2lMQ0pqYUdGcGNuQmxjbk52YmlJNlptRnNjMlY5Lkk2QXAweXZtQl9jS0JObWJHV3pOYUxTQUJ0TVJLdEs2cjBHNV8xNEN0MVhrYzE0a2lnaEwyeV85azlnY1I4dEt0eGVCNFlIekNRQW0wWUxUcU1KLUlnJTIyJTJDJTBBKysrKyUyMnVzZXJJZCUyMiUzQSslMjI") at OpenTokConference.m:267:3
    frame #8: 0x0000000100c79a70 Application Connect`-[OpenTokConference prepareForListeningCompletion:](self=0x000000028004cdd0, _cmd="prepareForListeningCompletion:", completion=0x0000000100cc7d48) at OpenTokConference.m:325:19
    frame #9: 0x0000000100c780bc Application Connect`-[OpenTokConference connectCompletion:](self=0x000000028004cdd0, _cmd="connectCompletion:", completion=0x0000000100cc7d48) at OpenTokConference.m:152:9
    frame #10: 0x0000000100cc7c04 Application Connect`-[Communication connectSessionsWithInfos:commonErrorText:completion:](self=0x0000000281843f70, _cmd="connectSessionsWithInfos:commonErrorText:completion:", sessionInfos=@"1 element", commonErrorText=0x93ccfeab85f34e17, completion=0x0000000100ca39fc) at Communication.m:140:9
    frame #11: 0x0000000100ca3984 Application Connect`__51-[InterviewVC connectVideoStreamingSessionIfNeeded]_block_invoke(.block_descriptor=0x00000002835c5800, pickedListeningSession=0x0000000282efd600) at InterviewVC.m:2430:9
    frame #12: 0x0000000100c94f28 Application Connect`__57-[InterviewVC updateSessionToken:incoming:visible:block:]_block_invoke_2.133(.block_descriptor=0x000000028358bc30) at InterviewVC.m:1101:13
    frame #13: 0x00000001041cc5a8 libdispatch.dylib`_dispatch_call_block_and_release + 32
    frame #14: 0x00000001041ce05c libdispatch.dylib`_dispatch_client_callout + 20
    frame #15: 0x00000001041de810 libdispatch.dylib`_dispatch_main_queue_drain + 1196
    frame #16: 0x00000001041de354 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 44
    frame #17: 0x00000001b720a6f8 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
    frame #18: 0x00000001b71ec058 CoreFoundation`__CFRunLoopRun + 2036
    frame #19: 0x00000001b71f0ed4 CoreFoundation`CFRunLoopRunSpecific + 612
    frame #20: 0x00000001f04f2368 GraphicsServices`GSEventRunModal + 164
    frame #21: 0x00000001b96cf3d0 UIKitCore`-[UIApplication _run] + 888
    frame #22: 0x00000001b96cf034 UIKitCore`UIApplicationMain + 340
    frame #23: 0x0000000100cce77c Interprefy Connect`main(argc=1, argv=0x000000016f1b36c0) at main.m:14:16
    frame #24: 0x00000001d5858960 dyld`start + 2528
  thread #3, name = 'gputools.smt_poll.0x283b5f760'
    frame #0: 0x00000001f3d72008 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x00000001be7927d8 libsystem_c.dylib`nanosleep + 220
    frame #2: 0x00000001be7934a4 libsystem_c.dylib`usleep + 68
    frame #3: 0x0000000102b2531c GPUToolsCapture`smt_poll_thread_entry(void*) + 108
    frame #4: 0x00000002041d46cc libsystem_pthread.dylib`_pthread_start + 148
  thread #7, name = 'com.apple.uikit.eventfetch-thread'
    frame #0: 0x00000001f3d71b48 libsystem_kernel.dylib`mach_msg2_trap + 8
    frame #1: 0x00000001f3d84008 libsystem_kernel.dylib`mach_msg2_internal + 80
    frame #2: 0x00000001f3d84248 libsystem_kernel.dylib`mach_msg_overwrite + 388
    frame #3: 0x00000001f3d7208c libsystem_kernel.dylib`mach_msg + 24
    frame #4: 0x00000001b71eaaf0 CoreFoundation`__CFRunLoopServiceMachPort + 160
    frame #5: 0x00000001b71ebd34 CoreFoundation`__CFRunLoopRun + 1232
    frame #6: 0x00000001b71f0ed4 CoreFoundation`CFRunLoopRunSpecific + 612
    frame #7: 0x00000001b158e334 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
    frame #8: 0x00000001b158e21c Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 64
    frame #9: 0x00000001b980433c UIKitCore`-[UIEventFetcher threadMain] + 436
    frame #10: 0x00000001b15a7808 Foundation`__NSThread__start__ + 716
    frame #11: 0x00000002041d46cc libsystem_pthread.dylib`_pthread_start + 148
  thread #10
    frame #0: 0x00000002041d3b90 libsystem_pthread.dylib`start_wqthread
  thread #14, name = 'com.apple.NSURLConnectionLoader'
    frame #0: 0x00000001f3d71b48 libsystem_kernel.dylib`mach_msg2_trap + 8
    frame #1: 0x00000001f3d84008 libsystem_kernel.dylib`mach_msg2_internal + 80
    frame #2: 0x00000001f3d84248 libsystem_kernel.dylib`mach_msg_overwrite + 388
    frame #3: 0x00000001f3d7208c libsystem_kernel.dylib`mach_msg + 24
    frame #4: 0x00000001b71eaaf0 CoreFoundation`__CFRunLoopServiceMachPort + 160
    frame #5: 0x00000001b71ebd34 CoreFoundation`__CFRunLoopRun + 1232
    frame #6: 0x00000001b71f0ed4 CoreFoundation`CFRunLoopRunSpecific + 612
    frame #7: 0x00000001b85485a8 CFNetwork`___lldb_unnamed_symbol14247 + 392
    frame #8: 0x00000001b15a7808 Foundation`__NSThread__start__ + 716
    frame #9: 0x00000002041d46cc libsystem_pthread.dylib`_pthread_start + 148
  thread #16
    frame #0: 0x00000002041d3b90 libsystem_pthread.dylib`start_wqthread
  thread #17
    frame #0: 0x00000002041d3b90 libsystem_pthread.dylib`start_wqthread
  thread #18
    frame #0: 0x00000001f3d72050 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #19
    frame #0: 0x00000002041d3b90 libsystem_pthread.dylib`start_wqthread
  thread #20
    frame #0: 0x00000001f3d72050 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #21
    frame #0: 0x00000001f3d72050 libsystem_kernel.dylib`__workq_kernreturn + 8
  thread #22, name = 'com.apple.coremedia.rootQueue.47'
    frame #0: 0x00000001f3d71adc libsystem_kernel.dylib`semaphore_timedwait_trap + 8
    frame #1: 0x00000001041ce804 libdispatch.dylib`_dispatch_sema4_timedwait + 64
    frame #2: 0x00000001041cee04 libdispatch.dylib`_dispatch_semaphore_wait_slow + 76
    frame #3: 0x00000001041e2240 libdispatch.dylib`_dispatch_worker_thread + 360
    frame #4: 0x00000002041d46cc libsystem_pthread.dylib`_pthread_start + 148
  thread #23, name = 'com.apple.coremedia.rootQueue.47'
    frame #0: 0x00000001f3d71adc libsystem_kernel.dylib`semaphore_timedwait_trap + 8
    frame #1: 0x00000001041ce804 libdispatch.dylib`_dispatch_sema4_timedwait + 64
    frame #2: 0x00000001041cee04 libdispatch.dylib`_dispatch_semaphore_wait_slow + 76
    frame #3: 0x00000001041e2240 libdispatch.dylib`_dispatch_worker_thread + 360
    frame #4: 0x00000002041d46cc libsystem_pthread.dylib`_pthread_start + 148
  thread #24
    frame #0: 0x0000000000000000
* thread #25, stop reason = signal SIGABRT
  * frame #0: 0x00000001f3d78200 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000002041da1ac libsystem_pthread.dylib`pthread_kill + 268
    frame #2: 0x00000001be7adc8c libsystem_c.dylib`abort + 180
    frame #3: 0x00000001c5588f2c libsystem_malloc.dylib`malloc_vreport + 908
    frame #4: 0x00000001c5589110 libsystem_malloc.dylib`malloc_report + 64
    frame #5: 0x00000001c5584b38 libsystem_malloc.dylib`find_zone_and_free + 308
    frame #6: 0x000000010168f534 Application Connect`ASN1_OBJECT_free + 100
    frame #7: 0x00000001011127b8 Application Connect`ASN1_primitive_free + 144
    frame #8: 0x0000000101112628 Application Connect`asn1_item_combine_free + 460
    frame #9: 0x0000000101112450 Application Connect`ASN1_item_free + 20
    frame #10: 0x000000010114c2ac Application Connect`sk_pop_free_ex + 68
    frame #11: 0x000000010114c2ac Application Connect`sk_pop_free_ex + 68
    frame #12: 0x0000000101155534 Application Connect`x509_name_canon + 688
    frame #13: 0x0000000101155090 Application Connect`x509_name_ex_d2i + 388
    frame #14: 0x00000001011112a0 Application Connect`asn1_template_noexp_d2i + 140
    frame #15: 0x0000000101110874 Application Connect`asn1_item_ex_d2i + 1332
    frame #16: 0x00000001011112a0 Application Connect`asn1_template_noexp_d2i + 140
    frame #17: 0x0000000101110874 Application Connect`asn1_item_ex_d2i + 1332
    frame #18: 0x0000000101110334 Application Connect`ASN1_item_ex_d2i + 20
    frame #19: 0x00000001011102fc Application Connect`ASN1_item_d2i + 68
    frame #20: 0x0000000101147800 Application Connect`parse_x509 + 44
    frame #21: 0x00000001011475e0 Application Connect`PEM_X509_INFO_read_bio + 372
    frame #22: 0x0000000100f68b80 Application Connect`otk_ssl_util_init_ssl_client_context + 988
    frame #23: 0x0000000100f4a4c4 Application Connect`otk_http_connect + 224
    frame #24: 0x0000000100f35280 Application Connect`otk_client_logging_send_bytes_impl + 440
    frame #25: 0x0000000100f3c348 Application Connect`otk_client_logging_configuration_file + 792
    frame #26: 0x0000000100f3c024 Application Connect`otk_client_logging_configuration_file_attempt + 60
    frame #27: 0x0000000100f71460 Application Connect`otk_anvil::otk_anvil_connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, OTK_ANVIL_SSL, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 292
    frame #28: 0x0000000100f301f8 Application Connect`otk_messenger_v2::connect(char const*, OTK_MESSENGER_V2_SSL, char const*, int, char const*, char const*, char const*, char const*) + 288
    frame #29: 0x0000000100f96d64 Application Connect`otk_session::connect_session(otk_session_connect_info*) + 1604
    frame #30: 0x0000000100f91e10 Application Connect`otk_session_invoke_msg + 136
    frame #31: 0x0000000100f59260 Application Connect`otk_ev_async_callback + 216
    frame #32: 0x0000000100fbbeb8 Application Connect`uv__async_event + 196
    frame #33: 0x0000000100fbc0b4 Application Connect`uv__async_io + 164
    frame #34: 0x0000000100fb5d38 Application Connect`uv__io_poll + 1148
    frame #35: 0x0000000100fb1b98 Application Connect`uv_run + 328
    frame #36: 0x0000000100f5993c Application Connect`otk_ev_thread_main + 88
    frame #37: 0x0000000100f197ac Application Connect`network_thread_main(void*) + 36
    frame #38: 0x00000002041d46cc libsystem_pthread.dylib`_pthread_start + 148

**Comment by IGitGotIt** [comment]
Trying to reproduce , using the token you have above I get an "invalid token format".
Can you send me the api key, session id and token separately to my email. 
Also  you can send me the token meta data you are embedding in the token , when you create it.

Thanks
jaideep.shah@vonge.com

**Comment by IGitGotIt** [comment]
> > Trying to reproduce , using the token you have above I get an "invalid token format". Can you send me the api key, session id and token separately to my email. Also you can send me the token meta data you are embedding in the token , when you create it.
> > Thanks [jaideep.shah@vonge.com](mailto:jaideep.shah@vonge.com)
> 
> @IGitGotIt We just realized today there is a typo in the provided email address [vonge.com](mailto:jaideep.shah@vonge.com) instead of vonage.com. The email was resent to [jaideep.shah@vonage.com](mailto:jaideep.shah@vonage.com)

I tried our Basic App (https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Basic-Video-Chat) with the credential you send me using 2.22.0 and 2.24.2 on a simulator (intel) and a device . Both worked ok w/o any token crash (2.22.0 has a background capture warning - which can be neglected for our tests). Can you try the Basic app with those versions and lmk.

Thanks
