### ISSUE TITLE
Camera indicator is on, although I am not publishing video.

### ISSUE THREAD

**Issue by VivekLalan** [opentok/opentok-ios-sdk-samples#276]
publisher.publishVideo = false
then too camera indicator is on all the time.

**Comment by v-kpheng** [comment]
@VivekLalan, thanks for letting us know about this issue.  An upcoming release will turn off the camera LED when video is muted (i.e., `publisher.publishVideo = false`).

Will keep you posted.

**Comment by v-kpheng** [comment]
Closing - this was fixed in iOS SDK 2.24.2.
