### ISSUE TITLE
Samples do not build on M1 mac (after update to OpenTok 2.24.2)

### ISSUE THREAD

**Issue by tikitu** [opentok/opentok-ios-sdk-samples#281]
**Describe the bug**
The iOS SDK v2.24.2 is [supposed to support simulators on Apple Silicon](https://tokbox.com/developer/sdks/ios/release-notes.html). However after updating to this version, the sample projects fail to build, complaining "Framework not found VonageWebRTC".

**To Reproduce**
Update the SDK version to 2.24.2, and try to build. I've opened #280 showing my working in more detail. I committed a bunch of lockfiles etc, hopefully this is enough to see what's going on.

Try to build the Basic-Video-Chat project.

**Expected behavior**
The project should build.

Instead, building fails with the error "Framework not found VonageWebRTC". 

**Device:**
- iOS SDK version: 2.24.2
- OS and version:

macOS Monterey Version 12.6.4
Mac mini (M1, 2020)
Xcode Version 14.2 (14C18) running _without_ Rosetta

Building for simulator iPhone 14 Pro, iOS 16.2

**Comment by tikitu** [comment]
(An equivalent exercise for the repo https://github.com/opentok/opentok-ios-sdk-samples-swift _does_ compile, by the way.)

**Comment by jvalli** [comment]
@tikitu You don't need to commit Cocoapods changes, please run `pod deintegrate` before generate a pull request.
Here is the fix for this issue: https://github.com/opentok/opentok-ios-sdk-samples/pull/286

**Comment by v-kpheng** [comment]
Thanks, @jvalli, for helping out.  @tikitu, the PR has been merged in.

**Comment by tikitu** [comment]
Thanks! I have a followup coming for the `-swift` sample, but this one is indeed dealt with.
