### ISSUE TITLE
otk_session::on_answer crash 

### ISSUE THREAD

**Issue by badarovska** [opentok/opentok-ios-sdk-samples#282]
In my production app I am getting KERN_INVALID_ADDRESS crash reports: 

otk_session::on_answer(otk_messenger_v2*, char const*, char const*, char const*, char const*, char const*, absl::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) + 1223320

Crashed: Thread #1
EXC_BAD_ACCESS KERN_INVALID_ADDRESS

Crash report: 
![Screenshot 2023-04-05 at 15 50 50](https://user-images.githubusercontent.com/17143444/230120646-d5bdfe21-2a24-471f-ade2-998dbd6e5f72.png)

I have not been able to reproduce this issue locally, so unfortunately I can not provide any reproduction steps. 
iOS SDK version: Opentok 2.24.1

**Comment by v-kpheng** [comment]
Thanks, @badarovska, for letting us know about this.

Nothing stands out from the stack trace unfortunately.  Do you have any steps to reproduce?  That would help immensely.  Please advise.  Thanks!

**Comment by badarovska** [comment]
Unfortunately, I have not been able to reproduce this. I've only seen this in the Crashlytics logs. I was hoping you'd have more info. I'll keep an eye out for this and let you know if I have any more information.
