### ISSUE TITLE
otk_peer_connection_manager::collect_garbage() crash 

### ISSUE THREAD

**Issue by badarovska** [opentok/opentok-ios-sdk-samples#284]
In the latest version of the SDK, I've been experiencing the following crash: 
otk_peer_connection_manager::collect_garbage() 

<img width="933" alt="Screenshot 2023-04-18 at 13 12 52" src="https://user-images.githubusercontent.com/17143444/232760239-8da0a8a2-be89-40ff-9f94-0045b6dec50e.png">

From what I can see in the logs, I am unable to provide any specific reproduction steps. 

Opentok SKD: iOS 2.25.0

**Comment by v-kpheng** [comment]
Thanks, @badarovska, for letting us know about this issue.

The stack trace doesn't reveal much though.  Nothing stands out, unfortunately.  Also, without steps to reproduce, there's not much we can do to help.  Sorry.

If you can provide steps to reproduce, or more details, that would help.
