### ISSUE TITLE
Unable to run test target with 2.25.2+ via cocoapods

### ISSUE THREAD

**Issue by civatrix** [opentok/opentok-ios-sdk-samples#291]
**Describe the bug**
Upgrading from 2.25.1 to 2.25.2 or 2.25.3 causes my framework test target crash at the following location:
`#0	0x00000001434148a0 in google::LogMessage::Init(char const*, int, int, void (google::LogMessage::*)()) ()`

The primary target builds and runs correctly, just the test target has this issue

**To Reproduce**
I have a repo you can use to [reproduce the isse](https://github.com/civatrix/OpenTokSample/), just open the `xcworkspace` and run the tests.

You can also recreate the project with a few steps:
1. Create a new Project in Xcode
2. Select `Framework` as the template
3. Enter any name but ensure `Include Tests` is checked
4. Run `pod init` to generate a default `Podfile`
5. Add `pod 'OTXCFramework', '2.25.3'` to the main target
6. Run `pod install`
7. Open the `xcworkspace` and run the tests

**Expected behavior**
Both app and test target should run correctly

**Device (please compete the following information):**
- Cocoapods 1.12.1
- Xcode 14.3

**Comment by v-kpheng** [comment]
Thanks, @civatrix, for letting us know about this.  This is being tracked internally: https://jira.vonage.com/browse/OW-625.

The fix should be out sometime this month in the 2.26.0 release.

**Comment by beHaze** [comment]
Fixed/released
