### ISSUE TITLE
Stability decrease since 2.25.0

### ISSUE THREAD

**Issue by badarovska** [opentok/opentok-ios-sdk-samples#294]
I've noticed a stability decrease since 2.25.0. I'm getting multiple EXC_BAD_ACCESS KERN_INVALID_ADDRESS crashed on my production app. Even after upgrading to 2.25.2  which fixes some memory leaks, there are still a lot of them happening. 

Some of the crashes: 

<img width="716" alt="Screenshot 2023-08-31 at 11 44 51" src="https://github.com/opentok/opentok-ios-sdk-samples/assets/17143444/b77f36c8-afbd-40bb-aded-abe47f6ee4d2">
<img width="726" alt="Screenshot 2023-08-31 at 11 45 03" src="https://github.com/opentok/opentok-ios-sdk-samples/assets/17143444/471e141f-f4a7-41de-8539-dad29fe5c413">
<img width="720" alt="Screenshot 2023-08-31 at 11 46 06" src="https://github.com/opentok/opentok-ios-sdk-samples/assets/17143444/b07ae482-09a5-423f-aa4b-ea0a5ee579b5">
<img width="713" alt="Screenshot 2023-08-31 at 11 46 23" src="https://github.com/opentok/opentok-ios-sdk-samples/assets/17143444/fde6ed48-0d66-4de9-854f-bb0aa7a21872">

- iOS SDK version: 2.25.0, 2.25.1, 2.25.2
- OS and version: multiple versions of iOS 15 and iOS 16

**Comment by yeuem141289** [comment]
@v-kpheng vk Version 2.26 have this crash too
When end call and set subscriber = nil, publisher = nil, otsession = nil
![Screenshot 2023-09-13 at 5 30 34 PM](https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/414aa162-3beb-45e4-8b87-e8480a0a8a9f)
![Screenshot 2023-09-13 at 5 31 02 PM](https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/2bc768e2-5dce-4bd3-9232-42ead185a6c4)

**Comment by v-kpheng** [comment]
@badarovska, @yeuem141289, are you able to reproduce this using one of our sample apps?  If so, which one?  Also, what are the steps you used to reproduce?

We suspect that there are some optimization flags being used, which should not be enabled.

**Comment by yeuem141289** [comment]
@v-kpheng k
Your samples is not crash because it is not release OTSession for frees memory. 
If you set OTSession = nil after end call it will be crashed.

**Comment by yeuem141289** [comment]
I fixed it by set         otSession = nil

**Comment by v-kpheng** [comment]
Thanks, @yeuem141289, for the heads up.  @badarovska, does that suggestion help you as well?

**Comment by badarovska** [comment]
@v-kpheng I will have to check out the proposed solution and get back to you.
