### ISSUE TITLE
Call 4g black after 1 minute 48 seconds

### ISSUE THREAD

**Issue by yeuem141289** [opentok/opentok-ios-sdk-samples#295]
https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/1451d41b-6408-4c6c-837a-6a45984ce245

**Describe the bug** 

Project samples is Basic-Video-Chat. I only custom UI.
I call from ipad (wifi) to iphone 6s (4g) and after 1 minute 48 seconds screen turn to black and without error. (Sometimes it throw error code 1022)

**To Reproduce**
Call video from ipad use Wifi and Iphone 6 use 4g

**Expected behavior**
Screen not turn to black

**Screenshots**

**Device (please compete the following information):**
Device:
- Iphone 6s ios 15.0.2 4g
- Ipad ios 14.0.1 wifi 
SDK OpenTok 2.26.0

**Additional context**

**Comment by yeuem141289** [comment]
My internet speed 
![C8AF3120-95E2-4D20-A23C-FFBFFD7BC828](https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/d64a11f0-10f9-49be-aa23-7e5b123baeaf)

**Comment by v-kpheng** [comment]
Thanks, @yeuem141289, for letting us know about this issue.

We perform a test with long running sessions, so this issue is surprising.  In any case, can you share a sessionId, please?  We can use it to investigate your test session.

**Comment by yeuem141289** [comment]
@v-kpheng I will send you session ID later. First here is my project test. Please check.
[Project Test.zip](https://github.com/opentok/opentok-ios-sdk-samples/files/12592245/Project.Test.zip)

**Comment by yeuem141289** [comment]
@v-kpheng I will send you session ID later. First here is my project test. Please check.
[Project Test.zip](https://github.com/opentok/opentok-ios-sdk-samples/files/12592253/Project.Test.zip)

**Comment by yeuem141289** [comment]
@v-kpheng I will send you session ID later. First here is my project test. Please check.
[Project Test.zip](https://github.com/opentok/opentok-ios-sdk-samples/files/12592259/Project.Test.zip)

**Comment by Shashi-Saurabh1** [comment]
Hi @v-kpheng , FYI, Customer shared the session id on ticket - 1_MX40NzE2NTg3NH5-MTY5MzM4NTA4NDA0Mn4vS2kzcGxqYTM0bVdIbFluZUVzUWsrRHF-fn4

**Comment by v-kpheng** [comment]
Closing, this you've reached out to Support.  Let's follow up through Support, moving forward, please.
