### ISSUE TITLE
Disconnect after join session success

### ISSUE THREAD

**Issue by yeuem141289** [opentok/opentok-ios-sdk-samples#298]
**Describe the bug**
After join session success call is disconnect

**Screenshots**

**Device (please compete the following information):**
- sessionId, if applicable: 
1_MX40NzE5NjU2NH5-MTY5Nzc5OTU0MjUyMH5EYlNxMVQ0VTNpbXRVVm1ScEJlZGZUOHV-fn4
2_MX40NzE5NjU2NH5-MTY5Nzc5OTU0Mzk4Nn5LRjVFdTdCbzVVSHRxNlFoVTVVUW9Edi9-fn4
2_MX40NzE5NjU2NH5-MTY5NzkyOTQ5MDYyOX5uOE92SjFZR0NnQ056QnBJNzQrVURxbEp-fn4

- iOS SDK version: 
- 2.17,2.26.0
- OS and version:
iPhone 13 Pro / iOS 17.0.3
iPhone XS Max / 16.6

**Additional context**
![Screenshot 2023-10-25 at 12 08 46 PM](https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/1c6a0ff4-f780-4ca4-a296-898e91d67ce7)
![Screenshot 2023-10-25 at 1 05 15 PM](https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/aa9f74b6-4727-4714-a102-f40aecea5c6f)

**Comment by v-kpheng** [comment]
@yeuem141289, thanks for letting us know about this issue.  Which sample app was used to reproduce this issue?  Also, were any changes made to the sample app?  If so, can you please share the modified sample app?  Or the details of the changes?  Thanks!

**Comment by yeuem141289** [comment]
@v-kpheng I have some apps user version sdk 2.17 and after update to 2.26.0 in one app it have some bugs about Interoperability. Can you guide me which version of tokbok Interoperability with 2.17. Thank you very much.
https://github.com/opentok/opentok-ios-sdk-samples/issues/298

**Comment by v-kpheng** [comment]
@yeuem141289, 2.17 has interoperability with 2.15 and 2.16.

**Comment by yeuem141289** [comment]
Thank you for your support. I understand
