### ISSUE TITLE
SDK require Privacy manifest 

### ISSUE THREAD

**Issue by yeuem141289** [opentok/opentok-ios-sdk-samples#308]
**Describe the bug**
Since Spring 2024 Apple require  SDK have Signed and Manifest file 
https://developer.apple.com/news/?id=r1henawx
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/videos/play/wwdc2023/10061/
Does tokbox SDK need do this? 
![Screenshot 2024-02-27 at 7 32 51 AM](https://github.com/opentok/opentok-ios-sdk-samples/assets/5528861/41779661-0485-48b7-b308-98ed3d928483)

**Comment by v-kpheng** [comment]
FYI, we're still investigating: https://jira.vonage.com/browse/OW-851.

**Comment by TheMakerOleguch** [comment]
Any update on this, folks? It's blocker after May 1 for release process

**Comment by phoriachyi** [comment]
wondering as well

**Comment by v-kpheng** [comment]
Apologies for the belated reply.  iOS SDK versions 2.25.5, 2.26.3, and 2.27.3 add support for the privacy manifests: https://tokbox.com/developer/sdks/ios/release-notes.html.
