### ISSUE TITLE
Screen share feature when application is in background state

### ISSUE THREAD

**Issue by ManojNuncsys** [opentok/opentok-ios-sdk-samples#312]
For screen sharing functionality, I have implemented broadcast upload extension and sending the captured frames to the publisher. When application is in active state screen share is working but when application enters into background publishing the captured frames is stopping.

While initiating publisher i am using custom video capture and sending the screen recorded frames using below method
[self.videoCaptureConsumer consumeImageBuffer:pixelBuffer
                                                     orientation:OTVideoOrientationUp
                                                       timestamp:time
                                                        metadata:nil];
In background modes Audio is enabled.

**Comment by v-kpheng** [comment]
@ManojNuncsys, can you please try https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Broadcast-Ext instead?
