### ISSUE TITLE
Green dot does not disappear even after the video call ends using OpenTok SDK

### ISSUE THREAD

**Issue by pradeepsingh02** [opentok/opentok-ios-sdk-samples#319]
Our app using OpenTok SDK for video calls. There is a green dot that appears in the top corner even after the video call ends. Due to this the users think we're doing something with the camera in the background which is not the case. 
I'd like to make the green dot go away after the video call ends. I can't seem to find a way remove this green dot after the call ends. We are just using the OpenTok SDK to make the video calls and not using the camera other than this. 
Can you please check why the green dot doesn't disappear after the call ends?

I am using OpenTok version - 'OpenTok', '~> 2.0'

Thanks

![IMG_8982](https://github.com/user-attachments/assets/474efd4e-b58d-4c5e-9915-199964595dce)

**Comment by v-kpheng** [comment]
@pradeepsingh02, which version of the iOS Client SDK are you using?  Also, on which models of iPhones are you able to reproduce with?
